use crate::core::FileReader;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExportOptions {
    pub format: String, // "hex", "c_array", "json"
    pub path: String,
    pub start: Option<usize>,
    pub end: Option<usize>,
}

/// Export data as hex dump.
#[tauri::command]
pub async fn export_hex(file_path: String, output_path: String, start: Option<usize>, end: Option<usize>) -> Result<(), String> {
    let reader = FileReader::open(&file_path).map_err(|e| e.to_string())?;
    let s = start.unwrap_or(0);
    let e = end.unwrap_or(reader.len());
    let data = reader.slice(s, e);

    let hex_dump: String = data
        .chunks(16)
        .enumerate()
        .map(|(i, chunk)| {
            let offset = s + i * 16;
            let hex: Vec<String> = chunk.iter().map(|b| format!("{:02X}", b)).collect();
            let ascii: String = chunk
                .iter()
                .map(|&b| if b >= 0x20 && b < 0x7F { b as char } else { '.' })
                .collect();
            format!("{:08X}  {:48}  {}", offset, hex.join(" "), ascii)
        })
        .collect::<Vec<_>>()
        .join("\n");

    std::fs::write(&output_path, hex_dump).map_err(|e| e.to_string())?;
    Ok(())
}

/// Export data as C byte array.
#[tauri::command]
pub async fn export_c_array(file_path: String, output_path: String, var_name: Option<String>) -> Result<(), String> {
    let reader = FileReader::open(&file_path).map_err(|e| e.to_string())?;
    let var = var_name.unwrap_or_else(|| "binary_data".to_string());

    let mut output = format!(
        "// Generated by Binary Insight\n// Source: {}\n// Size: {} bytes\n\n",
        file_path,
        reader.len()
    );

    output.push_str(&format!(
        "const unsigned char {}[{}] = {{\n",
        var,
        reader.len()
    ));

    for (i, chunk) in reader.data().chunks(16).enumerate() {
        output.push_str("    ");
        for (j, byte) in chunk.iter().enumerate() {
            output.push_str(&format!("0x{:02X}", byte));
            if i * 16 + j < reader.len() - 1 {
                output.push_str(", ");
            }
        }
        output.push('\n');
    }

    output.push_str("};\n");

    std::fs::write(&output_path, output).map_err(|e| e.to_string())?;
    Ok(())
}

/// Export analysis report as JSON.
#[tauri::command]
pub async fn export_json_report(file_path: String, output_path: String) -> Result<(), String> {
    let reader = FileReader::open(&file_path).map_err(|e| e.to_string())?;
    let info = reader.info();
    let format = crate::core::detect_file_format(reader.data());
    let regions = crate::formats::parse_file(reader.data(), &format);
    let entropy = crate::core::calculate_entropy(reader.data());
    let strings = reader.find_strings(6);

    let report = serde_json::json!({
        "file": {
            "path": info.path,
            "name": info.name,
            "size": info.size,
            "format": info.format,
            "sha256": info.sha256,
            "md5": info.md5,
        },
        "analysis": {
            "entropy": entropy,
            "regions": regions,
            "strings_count": strings.len(),
            "strings_sample": strings.iter().take(50).map(|(offset, s)| {
                serde_json::json!({"offset": offset, "value": s})
            }).collect::<Vec<_>>(),
        },
        "generated_by": "Binary Insight v1.0.0",
    });

    let json = serde_json::to_string_pretty(&report).map_err(|e| e.to_string())?;
    std::fs::write(&output_path, json).map_err(|e| e.to_string())?;
    Ok(())
}
